### ISSUE TITLE
I cannot find a website.

### ISSUE THREAD

**Issue by Pommesritter** [MothGirlMusic/hypnotranceme#1]
This page looks really interesting but i cannot see it as a website anywhere :(

**Comment by Pommesritter** [comment]
Still cannot load it.

What is this about?

**Comment by MothGirlMusic** [comment]
forgot to edit the DNS zoning when the IP changed. it should load now, give or take the 300 seconds for Time-To-Live..

I do hypnosis as a hobby sometimes. its just a group for people who follow me. the joke is that it looks all "cult-y" but its not... just a bunch of hypnosis enthusiast "furries".

**Comment by iceregent** [comment]
Hi :) remember me?

Huggs

**Comment by Pommesritter** [comment]
There are contents within the files which does not appear on the website. example:

> ..
DEEP SLEEP
BLANK MIND
...
Feeling hands on your head....
Turning your head from side to side..
Hands releasing your head...
Feeling your head sagging back down...
Lisfting your head slightly...
Eyes trying to focus in the dim light...
Seeing *him*..
Feeling his hands on your arm...
Seeing a needle in his hands..
Feeling fright.. aprehension..
Feeling the prick of the needle in your arm...
Feeling the hot fluid of hormones injected into your veins..
Mind going BLANK...
...
SLEEP NOW
DEEP SLEEP
BLANK MIND
ROBOT SLAVE
...
Feeling feminine hormones coursing thruout your body...
Shivering.. hanging from chains.. NAKED...
Mind going BLANK...
Images.. thoughts.. emotions.. fear.. confusion...
Feeling hands upon your body...
Razors.. shaving every last hair from your body...
leaving only your long, wavy hair on your head...
Shivers running thru your rapidly feminized body...
Handing.. chained.. naked...
Feeling your mind fading in and out...
One thing coming to the surface of yoru mind...
...
COCK
...

**Comment by iceregent** [comment]
Ohh.. your talking about my trances...

**Comment by MothGirlMusic** [comment]
> Hi :) remember me? Huggs

yes [@mothgirlmusic on telegram if you wish to chat more]

**Comment by MothGirlMusic** [comment]
> There are contents within the files which does not appear on the website. example:
> 
> > ..
> > DEEP SLEEP
> > BLANK MIND
> > ...
> > Feeling hands on your head....
> > Turning your head from side to side..
> > Hands releasing your head...
> > Feeling your head sagging back down...
> > Lisfting your head slightly...
> > Eyes trying to focus in the dim light...
> > Seeing _him_..
> > Feeling his hands on your arm...
> > Seeing a needle in his hands..
> > Feeling fright.. aprehension..
> > Feeling the prick of the needle in your arm...
> > Feeling the hot fluid of hormones injected into your veins..
> > Mind going BLANK...
> > ...
> > SLEEP NOW
> > DEEP SLEEP
> > BLANK MIND
> > ROBOT SLAVE
> > ...
> > Feeling feminine hormones coursing thruout your body...
> > Shivering.. hanging from chains.. NAKED...
> > Mind going BLANK...
> > Images.. thoughts.. emotions.. fear.. confusion...
> > Feeling hands upon your body...
> > Razors.. shaving every last hair from your body...
> > leaving only your long, wavy hair on your head...
> > Shivers running thru your rapidly feminized body...
> > Handing.. chained.. naked...
> > Feeling your mind fading in and out...
> > One thing coming to the surface of yoru mind...
> > ...
> > COCK
> > ...

not mine, i dont do sexual stuff. that's ice's

**Comment by Pommesritter** [comment]
Funny, i saw this kind of content before 👯

**Comment by Pommesritter** [comment]
I mean other websites :)
